"""Create service_actions table

Revision ID: 83424446da2a
Revises:
Create Date: 2025-06-28 13:41:06.104878

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "83424446da2a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_actions",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("service_prefix", sa.String(length=100), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=False),
        sa.Column("action_name", sa.String(length=255), nullable=False),
        sa.Column("action_url", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("access_level", sa.String(length=50), nullable=False),
        sa.Column("resource_types", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("condition_keys", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "access_level IN ('List', 'Read', 'Write', 'Permissions management', 'Tagging')",
            name="chk_access_level",
        ),
        sa.CheckConstraint(
            "action_url LIKE 'https://docs.aws.amazon.com%%'",
            name="chk_action_url_domain",
        ),
        sa.CheckConstraint(
            "id ~ '^[a-zA-Z0-9_-]+:[a-zA-Z0-9_*-]+$'", name="chk_id_format"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_actions_access_level"),
        "service_actions",
        ["access_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_actions_action_name"),
        "service_actions",
        ["action_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_actions_service_prefix"),
        "service_actions",
        ["service_prefix"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_actions_service_name"),
        "service_actions",
        ["service_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_actions_updated_at"),
        "service_actions",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_actions_updated_at"), table_name="service_actions")
    op.drop_index(op.f("ix_service_actions_service_name"), table_name="service_actions")
    op.drop_index(
        op.f("ix_service_actions_service_prefix"), table_name="service_actions"
    )
    op.drop_index(op.f("ix_service_actions_action_name"), table_name="service_actions")
    op.drop_index(op.f("ix_service_actions_access_level"), table_name="service_actions")
    op.drop_table("service_actions")
    # ### end Alembic commands ###
